name: Origins
version: '0.0.0.0.0.1'
main: codes.shiftmc.origins.Origins
loader: codes.shiftmc.origins.OriginLoader
description: Basicamente, racismo no Minecraft Vanilla 👍
api-version: '1.20.6'
folia-supported: true
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
