name: Origins
version: '${version}'
main: codes.shiftmc.origins.Origins
api-version: '1.20'
depend:
  - CommandAPI
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0